# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709726748df16041b64d9e296c4589a9d2554b14dc39b5a7a05d838d2549eef54c2e2429dc83fa6f875b27539fb5694c360d5e9701b6bd7c9d529933d8ca8cc6

test:
  secret_key_base: 97331873c614f324a333a60f11a16a28028e1bca7ad67873df343059df6d2d3b76ac3db02536b8f7e2b35a7ac6d26045e2e5253ba5f4e162750b38f73b36f7bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
